[[panels]]
position = "bottom"
applets = ["spacer", "clock"]

[[panels]]
position = "top"
applets = ["spacer","clock_custom", "clock", "battery", "battery_icon_only", "spacer", "tray" ]

[applets.clock_custom]
extends = "clock"
format = "%a %b %d, %H:%M:%S"
timezones = [
    {name= "Minsk", timezone= "Europe/Minsk", format= "%H:%M:%S"},
    {name= "St. Gallen", timezone= "Europe/Zurich"},
    {name="Tbilisi", timezone="Asia/Tbilisi"}
]

[applets.battery_icon_only]
extends = "battery"
label_on_battery = ""
label_on_ac = ""
tooltip_on_battery = ""
tooltip_on_ac = ""
