# [[panels]]
# position = "bottom"
# applets = ["spacer", "clock"]

[[panels]]
position = "top"
applets = ["pager", "sysinfo", "mpris", "spacer","clock_custom", "weather", "notifications", "privacy", "spacer", "tray", "keyboard", "network", "bluetooth", "audio", "battery", "session"]

[applets.clock_custom]
extends = "clock"
format = "%a %b %d, %H:%M"
timezones = [
    {name= "Minsk", timezone= "Europe/Minsk"},
    {name= "St. Gallen", timezone= "Europe/Zurich"},
    {name="St. Petersburg", timezone="Europe/Moscow"},
    {name="Tbilisi", timezone="Asia/Tbilisi"}
]

[applets.sysinfo]
extends = "exec"
command = ["/home/alex/projects/glimpse/var/sysstats/sysstats-applet"]

[applets.weather]
extends = "weather"
city_name = "Warsaw"
geolocate = false
hourly_slots = 5
forecast_days = 5

[applets.network]
extends = "network"
settings_command = "nm-connection-editor"

[applets.notifications]
extends = "notifications"
badge_style = "count"      # "dot" = accent dot, "count" = number (max 9+), "" = no badge

# [applets.audio]
# extends = "audio"
# show_icon = true                       # show volume icon
# label_format = "{volume} {device}"                      # empty = no label. Keys: {volume}, {device}
# tooltip_format = "{device} — {volume}%" # empty = no tooltip
# scroll_step = 5                        # volume change per scroll step (%)
# max_volume = 100                       # 100 = no overamplification, 150 = allow
# settings_command = "pavucontrol"       # empty = hide settings button

# [applets.battery_icon_only]
# extends = "battery"
# label_on_battery = ""
# label_on_ac = ""
# tooltip_on_battery = ""
# tooltip_on_ac = ""

[applets.keyboard]
extends = "keyboard"
format = "short"
per_window = true


[applets.exec_demo]
extends = "exec"
command = ["/home/alex/.config/glimpse/bin/custom_applet"]
restart_delay_ms = 10000

[wallpaper]
path = "/home/alex/wallpapers/tokyonight-02.jpg"
