pub mod backdrop;
pub mod bluetooth;
pub mod brightness;
pub mod calendar;
pub mod compositor;
mod compositors;
pub mod dbus;
pub mod display;
pub mod mpris;
pub mod network;
pub mod notifications;
pub mod privacy;
pub mod providers;
pub mod tray;
pub mod wallpaper;
