use std::{
    collections::HashSet,
    fs,
    path::{Path, PathBuf},
};

use glimpse::{
    compositor::CompositorKind,
    config::{BackdropConfig, Config, WallpaperConfig, WallpaperMode},
};

use crate::niri_managed;

pub const NIRI_BACKDROP_FRAGMENT: &str = "backdrop.kdl";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WallpaperGallerySource {
    System,
    Pictures,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WallpaperGalleryItem {
    pub path: PathBuf,
    pub source: WallpaperGallerySource,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BackgroundPersistStatus {
    Applied {
        config_path: PathBuf,
        managed_path: Option<PathBuf>,
        include_present: bool,
        reloaded: bool,
    },
    Unsupported,
}

pub fn wallpaper_search_roots() -> Vec<(WallpaperGallerySource, PathBuf)> {
    let mut roots = vec![(WallpaperGallerySource::System, PathBuf::from("/usr/share/backgrounds"))];
    if let Some(home) = std::env::var_os("HOME") {
        let home = PathBuf::from(home);
        roots.push((
            WallpaperGallerySource::Pictures,
            home.join("Pictures/Wallpapers"),
        ));
        roots.push((
            WallpaperGallerySource::Pictures,
            home.join("Pictures/Backgrounds"),
        ));
    }
    roots
}

pub fn scan_wallpaper_gallery(
    roots: &[(WallpaperGallerySource, PathBuf)],
) -> Vec<WallpaperGalleryItem> {
    let mut items = Vec::new();
    let mut seen = HashSet::new();

    for (source, root) in roots {
        let Ok(entries) = fs::read_dir(root) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_file() || !is_supported_wallpaper_path(&path) {
                continue;
            }
            let key = match fs::canonicalize(&path) {
                Ok(canonical) => canonical,
                Err(_) => path.clone(),
            };
            if !seen.insert(key) {
                continue;
            }
            items.push(WallpaperGalleryItem {
                path,
                source: *source,
            });
        }
    }

    items.sort_by(|left, right| {
        left.path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_lowercase()
            .cmp(
                &right
                    .path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .unwrap_or_default()
                    .to_lowercase(),
            )
    });
    items
}

pub fn is_supported_wallpaper_path(path: &Path) -> bool {
    matches!(
        path.extension()
            .and_then(|ext| ext.to_str())
            .map(|ext| ext.to_ascii_lowercase())
            .as_deref(),
        Some("png")
            | Some("jpg")
            | Some("jpeg")
            | Some("webp")
            | Some("bmp")
            | Some("heic")
            | Some("heif")
            | Some("avif")
    )
}

pub fn effective_backdrop_path(
    wallpaper: &WallpaperConfig,
    backdrop: &BackdropConfig,
) -> Option<PathBuf> {
    backdrop.path.clone().or_else(|| {
        if backdrop.enabled && wallpaper.mode == WallpaperMode::Image {
            wallpaper.path.clone()
        } else {
            None
        }
    })
}

pub fn apply_background_settings(
    compositor: CompositorKind,
    wallpaper: &WallpaperConfig,
    backdrop: &BackdropConfig,
) -> Result<BackgroundPersistStatus, String> {
    let config_path = Config::load().persist_background_settings(wallpaper, backdrop)?;
    if compositor != CompositorKind::Niri {
        return Ok(BackgroundPersistStatus::Applied {
            config_path,
            managed_path: None,
            include_present: false,
            reloaded: false,
        });
    }

    let managed_path = write_niri_backdrop_fragment()?;
    let index_path = niri_managed::update_niri_index(&[NIRI_BACKDROP_FRAGMENT])?;
    let include_present = niri_managed::detect_niri_include(&index_path);
    niri_managed::validate_niri_config(&managed_path)?;
    if include_present {
        niri_managed::reload_niri_config()?;
    }

    Ok(BackgroundPersistStatus::Applied {
        config_path,
        managed_path: Some(managed_path),
        include_present,
        reloaded: include_present,
    })
}

pub fn serialize_niri_backdrop_fragment() -> &'static str {
    "// Generated by Glimpse Settings. Manual edits may be overwritten.\nlayer-rule {\n    match namespace=\"^glimpse-backdrop$\"\n    place-within-backdrop true\n}\n"
}

pub fn managed_backdrop_runtime_path() -> Option<PathBuf> {
    niri_managed::managed_niri_dir_runtime_path().map(|path| path.join(NIRI_BACKDROP_FRAGMENT))
}

fn write_niri_backdrop_fragment() -> Result<PathBuf, String> {
    let Some(path) = managed_backdrop_runtime_path() else {
        return Err("HOME is not set".into());
    };
    let parent = path
        .parent()
        .ok_or("managed backdrop file has no parent directory")?;
    fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    fs::write(&path, serialize_niri_backdrop_fragment()).map_err(|error| error.to_string())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::{
        WallpaperGallerySource, effective_backdrop_path, is_supported_wallpaper_path,
        scan_wallpaper_gallery, serialize_niri_backdrop_fragment,
    };
    use glimpse::config::{BackdropConfig, ImageFit, WallpaperConfig, WallpaperMode};
    use std::{
        fs,
        path::{Path, PathBuf},
        time::{SystemTime, UNIX_EPOCH},
    };

    fn temp_dir(label: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock should work")
            .as_nanos();
        let path = std::env::temp_dir().join(format!("glimpse-background-{label}-{unique}"));
        fs::create_dir_all(&path).expect("temp dir should exist");
        path
    }

    #[test]
    fn scan_wallpaper_gallery_filters_supported_files_and_deduplicates() {
        let root = temp_dir("gallery");
        let system = root.join("system");
        let pictures = root.join("pictures");
        fs::create_dir_all(&system).expect("system dir should exist");
        fs::create_dir_all(&pictures).expect("pictures dir should exist");
        fs::write(system.join("one.png"), b"png").expect("png should be written");
        fs::write(system.join("skip.txt"), b"txt").expect("txt should be written");
        fs::write(pictures.join("one.png"), b"png").expect("duplicate path should be written");
        fs::write(pictures.join("two.webp"), b"webp").expect("webp should be written");

        let items = scan_wallpaper_gallery(&[
            (WallpaperGallerySource::System, system),
            (WallpaperGallerySource::Pictures, pictures),
        ]);

        assert_eq!(items.len(), 3);
        assert!(items.iter().all(|item| {
            item.path
                .extension()
                .and_then(|ext| ext.to_str())
                .is_some_and(|ext| ext != "txt")
        }));
    }

    #[test]
    fn effective_backdrop_path_falls_back_to_wallpaper_image() {
        let wallpaper = WallpaperConfig {
            color: "#112233".into(),
            transition_ms: 800,
            mode: WallpaperMode::Image,
            path: Some(PathBuf::from("/tmp/wallpaper.png")),
            fit: ImageFit::Cover,
        };
        let backdrop = BackdropConfig {
            enabled: true,
            path: None,
            blur_radius: 24,
        };

        assert_eq!(
            effective_backdrop_path(&wallpaper, &backdrop),
            Some(PathBuf::from("/tmp/wallpaper.png"))
        );
    }

    #[test]
    fn supported_wallpaper_extensions_include_heic_and_webp() {
        assert!(is_supported_wallpaper_path(Path::new("/tmp/test.heic")));
        assert!(is_supported_wallpaper_path(Path::new("/tmp/test.webp")));
        assert!(!is_supported_wallpaper_path(Path::new("/tmp/test.txt")));
    }

    #[test]
    fn niri_backdrop_fragment_targets_glimpse_backdrop_namespace() {
        let text = serialize_niri_backdrop_fragment();

        assert!(text.contains("glimpse-backdrop"));
        assert!(text.contains("place-within-backdrop true"));
    }
}
