use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

pub const NIRI_MANAGED_DIR: &str = ".config/niri/glimpse.d";
pub const NIRI_INDEX_FILE: &str = "index.kdl";

pub fn managed_niri_dir_runtime_path() -> Option<PathBuf> {
    let home = std::env::var_os("HOME")?;
    Some(PathBuf::from(home).join(NIRI_MANAGED_DIR))
}

pub fn managed_niri_index_runtime_path() -> Option<PathBuf> {
    managed_niri_dir_runtime_path().map(|path| path.join(NIRI_INDEX_FILE))
}

pub fn update_niri_index(required_fragments: &[&str]) -> Result<PathBuf, String> {
    let Some(index_path) = managed_niri_index_runtime_path() else {
        return Err("HOME is not set".into());
    };
    let parent = index_path
        .parent()
        .ok_or("managed index file has no parent directory")?;
    fs::create_dir_all(parent).map_err(|error| error.to_string())?;

    let mut fragments = existing_niri_fragments(parent);
    for fragment in required_fragments {
        if !fragments.iter().any(|existing| existing == fragment) {
            fragments.push((*fragment).to_string());
        }
    }
    fragments.sort();

    fs::write(&index_path, serialize_niri_index(&fragments)).map_err(|error| error.to_string())?;
    Ok(index_path)
}

pub fn detect_niri_include(managed_path: &Path) -> bool {
    let Some(home) = std::env::var_os("HOME") else {
        return false;
    };
    let config_path = PathBuf::from(home).join(".config/niri/config.kdl");
    let Ok(config) = fs::read_to_string(config_path) else {
        return false;
    };
    let managed = managed_path.to_string_lossy();
    niri_include_present(&config, &managed)
}

pub fn serialize_niri_index<T>(fragments: &[T]) -> String
where
    T: AsRef<str>,
{
    let mut output =
        String::from("// Generated by Glimpse Settings. Manual edits may be overwritten.\n");
    for fragment in fragments {
        output.push_str("include \"~/.config/niri/glimpse.d/");
        output.push_str(fragment.as_ref());
        output.push_str("\"\n");
    }
    output
}

pub fn validate_niri_config(path: &Path) -> Result<(), String> {
    let output = Command::new("niri")
        .args(["validate", "-c"])
        .arg(path)
        .output()
        .map_err(|error| format!("failed to run niri validate: {error}"))?;
    if output.status.success() {
        return Ok(());
    }

    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_owned();
    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    let message = if !stderr.is_empty() {
        stderr
    } else if !stdout.is_empty() {
        stdout
    } else {
        "niri rejected the generated config".to_owned()
    };
    Err(format!("niri validate failed: {message}"))
}

pub fn reload_niri_config() -> Result<(), String> {
    let output = Command::new("niri")
        .args(["msg", "action", "load-config-file"])
        .output()
        .map_err(|error| format!("failed to run niri reload: {error}"))?;
    if output.status.success() {
        return Ok(());
    }

    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_owned();
    if stderr.is_empty() {
        Err("niri rejected the generated config reload".into())
    } else {
        Err(format!("niri reload failed: {stderr}"))
    }
}

fn existing_niri_fragments(dir: &Path) -> Vec<String> {
    let mut fragments = Vec::new();
    let Ok(entries) = fs::read_dir(dir) else {
        return fragments;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if name == NIRI_INDEX_FILE || path.extension().and_then(|ext| ext.to_str()) != Some("kdl") {
            continue;
        }
        fragments.push(name.to_string());
    }

    fragments
}

fn niri_include_present(config: &str, managed_path: &str) -> bool {
    config.contains(managed_path)
        || config.contains("~/.config/niri/glimpse.d/index.kdl")
        || config.contains(".config/niri/glimpse.d/index.kdl")
}

#[cfg(test)]
mod tests {
    use super::serialize_niri_index;

    #[test]
    fn serialize_niri_index_includes_each_fragment() {
        let text = serialize_niri_index(&["backdrop.kdl", "displays.kdl"]);

        assert!(text.contains("include \"~/.config/niri/glimpse.d/backdrop.kdl\""));
        assert!(text.contains("include \"~/.config/niri/glimpse.d/displays.kdl\""));
    }
}
